### ISSUE TITLE
`fair pull` should determine whether data product exists and return a useful error

### ISSUE THREAD

**Issue by soniamitchell** [FAIRDataPipeline/FAIR-CLI#115] opened 2021-11-05 15:47 UTC
When attempting to read a data product that doesn't exist: 

```
Updating registry from config.yaml
WARNING:FAIRDataPipeline.ConfigYAML:Remote registry pulls are not yet implemented
InternalError: Version parsing failed for version=${{LATEST}}, free_write=False
```

**Comment by kzscisoft** [comment] 2021-11-15 13:43
This is just displaying the message @richardreeve put in whilst pull is not implemented and is therefore a duplicate of #7

**Closed by kzscisoft** 2021-11-15 13:43 UTC
